/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package boundaries;

import java.sql.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author allth
 */
public class JIFCrudArrondissement extends javax.swing.JInternalFrame {

    private Connection icn;

    /**
     * Creates new form JIFCrudArrondissement
     */
    public JIFCrudArrondissement() {
        initComponents();
        setVisible(true);

        PreparedStatement lpst;
        ResultSet lrs;
        String lsDSN;
        Object[] tEntetes;
        Object[][] tDataTable;
        Object[] tDataLigne;

        try {
            // Connexion à la DB
            lsDSN = "jdbc:mysql://127.0.0.1:3306/cinescope2017";
            icn = DriverManager.getConnection(lsDSN, "root", "");

            lpst = icn.prepareStatement("SELECT * FROM arrondissement");
            lrs = lpst.executeQuery();

            /*
             * Récupération de la structure du curseur
             * Le tableau d'Objet des en-têtes est rempli à partir des noms des 
             * colonnes du curseur grâce au ResultSetMetaData.
             */
            ResultSetMetaData lrsmd = lrs.getMetaData();
            // Nombre de colonnes du curseur
            int liColonnes = lrsmd.getColumnCount();
            // Noms des colonnes de la table
            tEntetes = new Object[liColonnes];
            for (int i = 0; i < liColonnes; i++) {
                tEntetes[i] = lrsmd.getColumnName(i + 1);
            }

            /* 
             * Pour l'insertion des données de la table dans la jTableArrondissement
             * Pour obtenir le nombre d'enregistrements et pouvoir dimensionner le tableau,
             * il faut se positionner sur le dernier enregistrement.
             */
            lrs.last();
            int liLignes = lrs.getRow();
            tDataTable = new Object[liLignes][liColonnes];

            lrs.beforeFirst();
            int i = 0;
            // Balayage des lignes
            while (lrs.next()) {
                // Balayage des colonnes pour construire une ligne
                tDataLigne = new Object[liColonnes];
                for (int j = 0; j < liColonnes; j++) {
                    if (lrs.getObject(j + 1) == null) {
                        tDataLigne[j] = "NUL";
                    } else {
                        tDataLigne[j] = lrs.getObject(j + 1).toString();
                    }
                }
                tDataTable[i] = tDataLigne;
                i++;
            }

            // La jTableArrondissement est remplie avec les deux tableaux créés
            jTableArrondissement.setModel(new DefaultTableModel(tDataTable, tEntetes));

            // Fermetures
            lrs.close();
            lpst.close();

        } catch (SQLException e) {
            jLabelMessage.setText(e.getMessage());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableArrondissement = new javax.swing.JTable();
        jLabelMessage = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldId = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldCode = new javax.swing.JTextField();
        jTextFieldNom = new javax.swing.JTextField();
        jLabelNom = new javax.swing.JLabel();
        jButtonAjout = new javax.swing.JButton();
        jButtonModifier = new javax.swing.JButton();
        jButtonSupprimer = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("CRUD Arrondissement");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jTableArrondissement.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableArrondissement.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableArrondissementMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableArrondissement);

        jLabelMessage.setText("Message");

        jLabel1.setText("Id");

        jTextFieldId.setEditable(false);
        jTextFieldId.setText("Id");

        jLabel2.setText("Code");

        jTextFieldCode.setText("Code");

        jTextFieldNom.setText("Nom");

        jLabelNom.setText("Nom");

        jButtonAjout.setText("Ajout");
        jButtonAjout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAjoutActionPerformed(evt);
            }
        });

        jButtonModifier.setText("Modifier");
        jButtonModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModifierActionPerformed(evt);
            }
        });

        jButtonSupprimer.setText("Supprimer");
        jButtonSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSupprimerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelMessage)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldId)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonAjout, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonModifier, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                            .addComponent(jTextFieldCode)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldNom)
                            .addComponent(jLabelNom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonSupprimer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(44, 44, 44))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabelNom))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAjout)
                    .addComponent(jButtonModifier)
                    .addComponent(jButtonSupprimer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jLabelMessage)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTableArrondissementMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableArrondissementMouseClicked
        // TODO add your handling code here:
        int selectedRow = this.jTableArrondissement.getSelectedRow();

        if (selectedRow >= 0) {
            jTextFieldId.setText(jTableArrondissement.getValueAt(selectedRow, 0).toString());
            jTextFieldCode.setText(jTableArrondissement.getValueAt(selectedRow, 1).toString());
            jTextFieldNom.setText(jTableArrondissement.getValueAt(selectedRow, 2).toString());
        } else {
            jLabelMessage.setText("Erreur");
        }
    }//GEN-LAST:event_jTableArrondissementMouseClicked

    private void jButtonAjoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAjoutActionPerformed
        // TODO add your handling code here:
         /*
         * Déclaration des attributs 
         */
        String lstSQL = "INSERT INTO arrondissement (CODE_arrondissement, NOM_arrondissement) VALUES(?,?)";
        String lsCode = jTextFieldCode.getText();
        String lsNom = jTextFieldNom.getText();
        // on copie le modèle de la jTable
        DefaultTableModel ldtm = (DefaultTableModel) jTableArrondissement.getModel();

        // Condition de vérification au niveau du remplissage des champs
        if (lsCode.isEmpty() || lsNom.isEmpty()) {
            jLabelMessage.setText("Veuillez indiquer le code et/ou le nom de l'arrondissement.");
        } else {
            /*
             * Bloc TRY pour la préparation de la requête SQL ainsi que la valorisation des
             * paramètres, suivi par l'exécution de celle-ci puis la fermeture du curseur.
             * Ensuite, bloc CATCH si une exception est levée durant l'opération.
             */
            try {
                PreparedStatement lpst = icn.prepareStatement(lstSQL, Statement.RETURN_GENERATED_KEYS);

                lpst.setString(1, lsCode);
                lpst.setString(2, lsNom);

                Object[] tLigne;
                int liAffecte = lpst.executeUpdate();
                // Si l'ordre a bien été exécuté, affichage d'un message de réussite
                if (liAffecte == 1) {
                    ResultSet lrsNouvelleCle = lpst.getGeneratedKeys();
                    if (lrsNouvelleCle.next()) {
                        tLigne = new Object[3];
                        tLigne[0] = lrsNouvelleCle.getInt(1);
                        tLigne[1] = lsCode;
                        tLigne[2] = lsNom;
                        // ajout de la ligne dans le jTable
                        ldtm.addRow(tLigne);
                        // message
                        jLabelMessage.setText("L'arrondissement " + jTextFieldNom.getText() + " a bien été ajouté.");
                    }
                    // Sinon affiche comme quoi il y a eu un incident
                } else {
                    jLabelMessage.setText("Erreur dans l'insertion.");
                }
                lpst.close();

            } catch (SQLException ex) {
                jLabelMessage.setText(ex.getMessage());
            }
        }
    }//GEN-LAST:event_jButtonAjoutActionPerformed

    private void jButtonModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModifierActionPerformed
        // TODO add your handling code here:
        /*
         * Déclaration des attributs 
         */
        PreparedStatement lpst;
        String lsUpdate = "UPDATE arrondissement SET CODE_arrondissement = ?, NOM_arrondissement = ? WHERE ID_arrondissement = ?";
        String lsCode = jTextFieldCode.getText().toString();
        String lsNom = jTextFieldNom.getText().toString();
        String lsId = jTextFieldId.getText().toString();
        int selectedRow = this.jTableArrondissement.getSelectedRow();

        /*
         * Bloc TRY pour la préparation de la requête SQL ainsi que la valorisation des
         * paramètres, suivi par l'exécution de celle-ci puis la fermeture du curseur.
         * Ensuite, bloc CATCH si une exception est levée durant l'opération.
         */
        try {
            lpst = icn.prepareStatement(lsUpdate);

            lpst.setString(1, lsCode);
            lpst.setString(2, lsNom);
            lpst.setString(3, lsId);

            int liAffecte = lpst.executeUpdate();

            if (liAffecte == 1) {
                if (selectedRow >= 0) {
                    // On modifie la ligne de la jTable qui vient d'être modifié
                    jTableArrondissement.setValueAt(lsId, selectedRow, 0);
                    jTableArrondissement.setValueAt(lsCode, selectedRow, 1);
                    jTableArrondissement.setValueAt(lsNom, selectedRow, 2);
                    // message
                    jLabelMessage.setText("L'arrondissement " + jTextFieldNom.getText() + " a bien été modifié.");
                } else {
                    jLabelMessage.setText("Erreur");
                }
            }
            lpst.close();

        } catch (SQLException ex) {
            jLabelMessage.setText(ex.getMessage());
        }
    }//GEN-LAST:event_jButtonModifierActionPerformed

    private void jButtonSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSupprimerActionPerformed
        // TODO add your handling code here:
        /*
         * Déclaration des attributs 
         */
        PreparedStatement lpst;
        String lsId = jTextFieldId.getText().toString();
        String lsDelete = "DELETE FROM arrondissement WHERE ID_arrondissement = ?";
        DefaultTableModel ldtm = (DefaultTableModel) jTableArrondissement.getModel();
        int selectedRow = this.jTableArrondissement.getSelectedRow();


        /*
         * Bloc TRY pour la préparation de la requête SQL ainsi que la valorisation des
         * paramètres, suivi par l'exécution de celle-ci puis la fermeture du curseur.
         * Ensuite, bloc CATCH si une exception est levée durant l'opération.
         */
        try {
            lpst = icn.prepareStatement(lsDelete);

            lpst.setString(1, lsId);
            int liAffecte = lpst.executeUpdate();

            if (liAffecte == 1) {
                if (selectedRow >= 0) {
                    // efface la ligne de la jTable supprimée dans la bd
                    ldtm.removeRow(selectedRow);
                    // message
                    jLabelMessage.setText("L'arrondissement " + jTextFieldNom.getText() + " a bien été supprimé.");
                } else {
                    jLabelMessage.setText("Erreur");
                }
            }
            lpst.close();
            jLabelMessage.setText("L'arrondissement " + jTextFieldNom.getText() + " a bien été supprimé.");

        } catch (SQLException ex) {
            jLabelMessage.setText(ex.getMessage());
        }
    }//GEN-LAST:event_jButtonSupprimerActionPerformed

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        // TODO add your handling code here:
        // DECONNEXION DE LA BD
        try {
            icn.close();
        } catch (SQLException ex) {
            System.err.println(ex.getMessage());
        }
    }//GEN-LAST:event_formInternalFrameClosing


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAjout;
    private javax.swing.JButton jButtonModifier;
    private javax.swing.JButton jButtonSupprimer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelMessage;
    private javax.swing.JLabel jLabelNom;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableArrondissement;
    private javax.swing.JTextField jTextFieldCode;
    private javax.swing.JTextField jTextFieldId;
    private javax.swing.JTextField jTextFieldNom;
    // End of variables declaration//GEN-END:variables
}
