/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package boundaries;

import daos.DepartementDAO;
import daos.Globale;
import entities.Departement;
import java.sql.*;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author allth
 */
public class JIFDepartementCRUD extends javax.swing.JInternalFrame {

    private DefaultTableModel idtm;
    private Connection icnx;

    /**
     * Creates new form JIFDepartementCRUD
     */
    public JIFDepartementCRUD() {
        initComponents();

        idtm = (DefaultTableModel) jTableDepartement.getModel();

        icnx = Globale.getCnx();
        DepartementDAO daoS = new DepartementDAO(icnx);
        List<Departement> liste = daoS.select();
        Departement dep;
        Object[] tLigne;
        for (int i = 0; i < liste.size(); i++) {
            dep = liste.get(i);
            tLigne = new Object[3];
            tLigne[0] = dep.getIdDepartement();
            tLigne[1] = dep.getCodeDepartement();
            tLigne[2] = dep.getNomDepartement();
            System.out.println(tLigne[0].toString());
            idtm.addRow(tLigne);
        }

        setVisible(true);

    }

    /**
     *
     */
    private void remplirJTable() {

        for (int i = idtm.getRowCount() - 1; i >= 0; i--) {
            idtm.removeRow(i);
        }

        try {
            Object[] tLigne;
            DepartementDAO dao = new DepartementDAO(icnx);
            List<Departement> liste = dao.select();
            for (int i = 0; i < liste.size(); i++) {
                Departement departement = liste.get(i);
                tLigne = new Object[3];
                tLigne[0] = departement.getIdDepartement();
                tLigne[1] = departement.getCodeDepartement();
                tLigne[2] = departement.getNomDepartement();
                idtm.addRow(tLigne);
            }

            jLabelMessage.setText("Okay !!!");

        } catch (Exception ex) {
            jLabelMessage.setText(ex.getMessage());
        }

    } /// remplirJTable

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDepartement = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButtonClear = new javax.swing.JButton();
        jButtonAjout = new javax.swing.JButton();
        jButtonModifier = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jLabelMessage = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jTableDepartement.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id_departement", "code_departement", "nom_departement"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableDepartement.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableDepartementMouseClicked(evt);
            }
        });
        jTableDepartement.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTableDepartementKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTableDepartement);

        jTextField1.setEditable(false);
        jTextField1.setText("id");

        jTextField2.setText("27");

        jTextField3.setText("Eure");
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jLabel1.setText("Id");

        jLabel2.setText("Code Departement");

        jLabel3.setText("Nom Departement");

        jButtonClear.setText("Clear");
        jButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearActionPerformed(evt);
            }
        });

        jButtonAjout.setText("Add");
        jButtonAjout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAjoutActionPerformed(evt);
            }
        });

        jButtonModifier.setText("Update");
        jButtonModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModifierActionPerformed(evt);
            }
        });

        jButtonDelete.setText("Delete");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });

        jLabelMessage.setText("Message");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelMessage)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButtonClear)
                                        .addGap(42, 42, 42)
                                        .addComponent(jButtonAjout)
                                        .addGap(44, 44, 44)
                                        .addComponent(jButtonModifier))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3))
                                        .addGap(80, 80, 80)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextField1)
                                            .addComponent(jTextField2)
                                            .addComponent(jTextField3))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonDelete)))
                        .addGap(55, 55, 55))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonAjout, jButtonClear, jButtonDelete, jButtonModifier});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonClear)
                    .addComponent(jButtonAjout)
                    .addComponent(jButtonModifier)
                    .addComponent(jButtonDelete))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jLabelMessage)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTableDepartementMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableDepartementMouseClicked
        // TODO add your handling code here:
        int selectedRow = this.jTableDepartement.getSelectedRow();

        if (selectedRow >= 0) {
            jTextField1.setText(jTableDepartement.getValueAt(selectedRow, 0).toString());
            jTextField2.setText(jTableDepartement.getValueAt(selectedRow, 1).toString());
            jTextField3.setText(jTableDepartement.getValueAt(selectedRow, 2).toString());
        } else {
            jLabelMessage.setText("Erreur");
        }


    }//GEN-LAST:event_jTableDepartementMouseClicked

    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearActionPerformed
        // TODO add your handling code here:
        jTextField1.setText("id");
        jTextField2.setText("");
        jTextField3.setText("");
    }//GEN-LAST:event_jButtonClearActionPerformed

    private void jButtonAjoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAjoutActionPerformed
        // TODO add your handling code here:

        idtm = (DefaultTableModel) jTableDepartement.getModel();

        Departement d = new Departement(jTextField2.getText(), jTextField3.getText());
        DepartementDAO daoI = new DepartementDAO(icnx);
        int r = daoI.insert(d);
        jLabelMessage.setText(r + " enregistrement a été effectué");
        if (r == 1) {
            Object[] tLigne = new Object[3];
            tLigne[0] = d.getIdDepartement();
            tLigne[1] = d.getCodeDepartement();
            tLigne[2] = d.getNomDepartement();
            idtm.addRow(tLigne);
            jLabelMessage.setText(r + " enregistrement a été effectué");
        } else {
            jLabelMessage.setText("Aucun enregistrement a été effectué");
        }
    }//GEN-LAST:event_jButtonAjoutActionPerformed

    private void jButtonModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModifierActionPerformed
        // TODO add your handling code here:
        if (jTextField1.getText().equals("id")) {
            jLabelMessage.setText("Veuillez selectionner un Departement");
        } else {
            int liAffecte = 0;

            try {
                DepartementDAO dao = new DepartementDAO(icnx);

                // Update
                Departement di = new Departement(Integer.valueOf(jTextField1.getText()), jTextField2.getText(), jTextField3.getText());
                liAffecte = dao.update(di);
                if (liAffecte == 1) {
                    icnx.commit();
                }
                jLabelMessage.setText("Modifié : " + Integer.toString(liAffecte));
                remplirJTable();
            } catch (SQLException e) {
                jLabelMessage.setText(e.getMessage());
            }
        }

    }//GEN-LAST:event_jButtonModifierActionPerformed

    private void jTableDepartementKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableDepartementKeyReleased
        // TODO add your handling code here:
        jTableDepartementMouseClicked(null);
    }//GEN-LAST:event_jTableDepartementKeyReleased

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        // TODO add your handling code here:
        if (jTextField1.getText().equals("id")) {
            jLabelMessage.setText("Veuillez sélectionner une ligne !");
        } else {
            try {
                DepartementDAO dao = new DepartementDAO(icnx);

                // Delete
                Departement dd = new Departement(Integer.valueOf(jTextField1.getText()), jTextField2.getText(), jTextField3.getText());
                int liAffecte = dao.delete(dd);
                icnx.commit();
                if (liAffecte == 1) {
                    icnx.commit();
                    remplirJTable();
                }
                jLabelMessage.setText("Supprimé : " + Integer.toString(liAffecte));

            } catch (SQLException e) {
                jLabelMessage.setText(e.getMessage());
            }
        }
    }//GEN-LAST:event_jButtonDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAjout;
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonModifier;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelMessage;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableDepartement;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
