/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package boundaries;

import java.sql.*;

/**
 *
 * @author allth
 */
public class JIFPaysAjout extends javax.swing.JInternalFrame {

    /**
     * Creates new form JIFPaysAjout
     */
    public JIFPaysAjout() {
        initComponents();

        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldPays = new javax.swing.JTextField();
        jTextFieldMasculin = new javax.swing.JTextField();
        jTextFieldFeminin = new javax.swing.JTextField();
        jTextFieldNeutre = new javax.swing.JTextField();
        jButtonAjouter = new javax.swing.JButton();
        jLabel1Pays = new javax.swing.JLabel();
        jLabelMasculin = new javax.swing.JLabel();
        jLabelFeminin = new javax.swing.JLabel();
        jLabelNeutre = new javax.swing.JLabel();
        jLabelMessage = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Ajout Pays");

        jTextFieldPays.setText("Roumanie");

        jTextFieldMasculin.setText("Roumain");
        jTextFieldMasculin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMasculinActionPerformed(evt);
            }
        });

        jTextFieldFeminin.setText("Roumaine");

        jTextFieldNeutre.setText("Roumano");

        jButtonAjouter.setText("Ajouter");
        jButtonAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAjouterActionPerformed(evt);
            }
        });

        jLabel1Pays.setText("Pays");

        jLabelMasculin.setText("Masculin");

        jLabelFeminin.setText("Féminin");

        jLabelNeutre.setText("Neutre");

        jLabelMessage.setText("Message");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelFeminin)
                            .addComponent(jLabelMasculin)
                            .addComponent(jLabel1Pays))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldMasculin, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldFeminin, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldPays, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelNeutre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonAjouter, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                            .addComponent(jTextFieldNeutre)))
                    .addComponent(jLabelMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(35, 35, 35))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldPays)
                    .addComponent(jLabel1Pays, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldMasculin)
                    .addComponent(jLabelMasculin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldFeminin)
                    .addComponent(jLabelFeminin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNeutre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNeutre, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addComponent(jButtonAjouter)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(jLabelMessage)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldMasculinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMasculinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMasculinActionPerformed

    private void jButtonAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAjouterActionPerformed
        // TODO add your handling code here:

        if (jTextFieldPays.getText().isEmpty() || jTextFieldMasculin.getText().isEmpty() || jTextFieldFeminin.getText().isEmpty() || jTextFieldNeutre.getText().isEmpty()) {
            jLabelMessage.setText("Toutes les saisies sont obligatoires!!");
        } else {
            try {
                // --- Connexion
                String lsDSN;
                lsDSN = "jdbc:mysql://127.0.0.1:3306/cinescope2017";
                Connection lcn = DriverManager.getConnection(lsDSN, "root", "");

                // --- INSERT
                String lsSQL = "INSERT INTO pays (NOM_pays, MASCULIN, FEMININ, NEUTRE) VALUES(?,?,?,?)";

                // --- Creation de l'objet "commande SQL" et ...
                PreparedStatement lpst = lcn.prepareStatement(lsSQL, Statement.RETURN_GENERATED_KEYS);

            // --- Valorisation du ou des parametre(s)
                // --- Les valeurs pourraient etre saisies au clavier
                lpst.setString(1, jTextFieldPays.getText());
                lpst.setString(2, jTextFieldMasculin.getText());
                lpst.setString(3, jTextFieldFeminin.getText());
                lpst.setString(4, jTextFieldNeutre.getText());

                // --- Execution de la requete
                int liAffecte = lpst.executeUpdate();
                //on teste le resultat
                if (liAffecte == 1) {
                    ResultSet lrsNouvelleCle = lpst.getGeneratedKeys();
                    if (lrsNouvelleCle.next()) {
                        int liNewID = lrsNouvelleCle.getInt(1);
                        jLabelMessage.setText(" Insertion réussi avec pour id : " + liNewID);
                    }
                } else {
                    jLabelMessage.setText("Erreur dans l'insertion");
                }
                lpst.close();
                lcn.close();

            } catch (SQLException ex) {
                jLabelMessage.setText(ex.getMessage());
            }
        }
    }//GEN-LAST:event_jButtonAjouterActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAjouter;
    private javax.swing.JLabel jLabel1Pays;
    private javax.swing.JLabel jLabelFeminin;
    private javax.swing.JLabel jLabelMasculin;
    private javax.swing.JLabel jLabelMessage;
    private javax.swing.JLabel jLabelNeutre;
    private javax.swing.JTextField jTextFieldFeminin;
    private javax.swing.JTextField jTextFieldMasculin;
    private javax.swing.JTextField jTextFieldNeutre;
    private javax.swing.JTextField jTextFieldPays;
    // End of variables declaration//GEN-END:variables
}
