/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package boundaries;

import java.sql.*;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author allth
 */
public class JIFPaysSuppression extends javax.swing.JInternalFrame {

    private Connection icn;
    private DefaultComboBoxModel idcbm;

    /**
     * Creates new form JIFPaysAjout
     */
    public JIFPaysSuppression() {
        initComponents();
        setVisible(true);
        setTitle("Suppression Pays");

        try {
            // --- Connexion
            Class.forName("org.gjt.mm.mysql.Driver");
            String lsDSN = "jdbc:mysql://127.0.0.1:3306/cinescope2017";
            icn = DriverManager.getConnection(lsDSN, "root", "");

            Statement lstSQL = icn.createStatement();
            ResultSet lrs = lstSQL.executeQuery("SELECT NOM_pays FROM pays ORDER BY 1 DESC");

            idcbm = new DefaultComboBoxModel();
            //idcbm.addElement("");
            while (lrs.next()) {
                //jComboBoxPays.addItem(lrs.getString(1));
                idcbm.addElement(lrs.getString(1));
            }
            jComboBoxSuppressionPays.setModel(idcbm);

            lrs.close();
            lstSQL.close();
            jLabelMessage.setText("");
            
        } catch (ClassNotFoundException | SQLException ex) {
            jLabelMessage.setText(ex.getMessage());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonSupprimer = new javax.swing.JButton();
        jLabelMessage = new javax.swing.JLabel();
        jComboBoxSuppressionPays = new javax.swing.JComboBox();
        jLabelSuppr = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Suppression d'un Pays");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jButtonSupprimer.setText("Supprimer");
        jButtonSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSupprimerActionPerformed(evt);
            }
        });

        jLabelMessage.setText("message");

        jComboBoxSuppressionPays.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--Selectionnez--" }));
        jComboBoxSuppressionPays.setToolTipText("");
        jComboBoxSuppressionPays.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSuppressionPaysActionPerformed(evt);
            }
        });

        jLabelSuppr.setText("Pays à supprimer :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonSupprimer, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                    .addComponent(jLabelMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabelSuppr)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(jComboBoxSuppressionPays, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBoxSuppressionPays)
                    .addComponent(jLabelSuppr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(41, 41, 41)
                .addComponent(jButtonSupprimer)
                .addGap(18, 18, 18)
                .addComponent(jLabelMessage)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSupprimerActionPerformed
        // TODO add your handling code here:
        try {

            // DELETE
            String lsSQL = "DELETE FROM pays WHERE NOM_pays=?";

            PreparedStatement lpst = icn.prepareStatement(lsSQL);

            lpst.setString(1, jComboBoxSuppressionPays.getSelectedItem().toString());

            lpst.executeUpdate();

            lpst.close();
            
            idcbm.removeElement(jComboBoxSuppressionPays.getSelectedItem().toString());

            jLabelMessage.setText("Okay pour la suppression !!!");

        } catch (SQLException ex) {
            jLabelMessage.setText(ex.getMessage());
        }
    }//GEN-LAST:event_jButtonSupprimerActionPerformed

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        // TODO add your handling code here:
        try {
            icn.close();
        } catch (SQLException e) {
            System.err.println(e.getMessage());
        }
    }//GEN-LAST:event_formInternalFrameClosing

    private void jComboBoxSuppressionPaysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSuppressionPaysActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxSuppressionPaysActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSupprimer;
    private javax.swing.JComboBox jComboBoxSuppressionPays;
    private javax.swing.JLabel jLabelMessage;
    private javax.swing.JLabel jLabelSuppr;
    // End of variables declaration//GEN-END:variables
}
