/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package boundaries;

import java.sql.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author allth
 */
public class JIFPaysVisu extends javax.swing.JInternalFrame {

    /**
     * Creates new form JIFPaysVisu
     */
    public JIFPaysVisu() {
        initComponents();
        setVisible(true);

        try {
            // Connexion a la bd
            Connection lcn = DriverManager.getConnection("jdbc:mysql://127.0.0.1:3306/cinescope2017", "root", "");
            //on prepare l'ordre SQL (ici pas utile car il n'y a pas de paramètres)
            PreparedStatement lpst = lcn.prepareStatement("SELECT * FROM pays");
            // On execute l'odre SQL
            ResultSet lrs = lpst.executeQuery();
            
            // On déclare un tableau d'objet
            Object[] tLigne;
            
            // on copie le modèle de la jTable
            DefaultTableModel ldtm = (DefaultTableModel) jTableVisuPays.getModel();
            
            // a chaque ligne du resultat du curseur récupérer sur l'ordre SQL (while)
            while (lrs.next()) {
                // on crée un tableau d'objet de 5 attributs
                tLigne = new Object[5];
                // a chaque resultat de la ligne du curseur, on l'incorpore
                tLigne[0] = lrs.getString(1);
                tLigne[1] = lrs.getString(2);
                tLigne[2] = lrs.getString(3);
                tLigne[3] = lrs.getString(4);
                tLigne[4] = lrs.getString(5);
                
                // on ajoute le tableau a une ligne du jTable
                ldtm.addRow(tLigne);
            }

            lrs.close();
            lpst.close();
            lcn.close();

            jLabelMessage.setText("Jusque là tout va bien !!!");

        } catch (SQLException e) {
            jLabelMessage.setText(e.getMessage());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableVisuPays = new javax.swing.JTable();
        jLabelMessage = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Visu Pays");

        jTableVisuPays.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID_pays", "NOM_pays", "MASCULIN", "FEMININ", "NEUTRE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableVisuPays);

        jLabelMessage.setText("Message");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelMessage)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelMessage;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableVisuPays;
    // End of variables declaration//GEN-END:variables
}
