/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package boundaries;

import daos.Globale;
import java.sql.*;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author allth
 */
public class JIFVGenerateCrud extends javax.swing.JInternalFrame {

    private Connection icn;
    private DefaultComboBoxModel idcbm;
    private JLabel[] tLabels;
    private JTextField[] tJTexts;
    private DefaultTableModel idtm;

    /**
     * Creates new form JIFVGenerateCrud
     */
    public JIFVGenerateCrud() {
        initComponents();
        setVisible(true);

        setTitle("Generate CRUD");

        try {
            // --- Connexion

            icn = Globale.getCnx();

            Statement lstSQL = icn.createStatement();

            ResultSet lrs = lstSQL.executeQuery("SELECT * from pays");

            DatabaseMetaData ldbmd;
            // --- Acces a la metabase, au dictionnaire
            ldbmd = icn.getMetaData();

            // On recupère les nom des tables de la base de donnée en question
            String tTypes[] = null;
            ResultSet lrsTables = ldbmd.getTables("cinescope2017", "", "",tTypes);

            idcbm = new DefaultComboBoxModel();
            //idcbm.addElement("");
            while (lrsTables.next()) {
                //jComboBoxPays.addItem(lrs.getString(1));
                idcbm.addElement(lrsTables.getString(3));
            }
            jComboBoxGenerate.setModel(idcbm);
            lrsTables.close();
            
            lrs.close();
            lstSQL.close();
            jLabelMessage.setText("");

        } catch (SQLException ex) {
            jLabelMessage.setText(ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabelMessage = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxGenerate = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabelMessage.setText("Message");

        jLabel1.setText("Selectionnez la table à afficher :");

        jComboBoxGenerate.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxGenerateItemStateChanged(evt);
            }
        });

        jPanel1.setAutoscrolls(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 167, Short.MAX_VALUE)
        );

        jButton1.setText("Clear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Add");

        jButton3.setText("Delete");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Update");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("jButton5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton5))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(87, 87, 87)
                        .addComponent(jComboBoxGenerate, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabelMessage)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE))
                .addContainerGap(79, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton1, jButton2, jButton3, jButton4, jButton5});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBoxGenerate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelMessage)
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton1, jButton2, jButton3, jButton4, jButton5});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxGenerateItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxGenerateItemStateChanged
        // TODO add your handling code here:

        PreparedStatement lpst;
        ResultSet lrs;
        String lsDSN;
        Object[] tEntetes;
        Object[][] tDataTable;
        Object[] tDataLigne;

        try {
            // Connexion à la DB
            lsDSN = "jdbc:mysql://127.0.0.1:3306/cinescope2017";
            icn = DriverManager.getConnection(lsDSN, "root", "");

            lpst = icn.prepareStatement("SELECT * FROM " + jComboBoxGenerate.getSelectedItem().toString());
            lrs = lpst.executeQuery();

            /*
             * Récupération de la structure du curseur
             * Le tableau d'Objet des en-têtes est rempli à partir des noms des 
             * colonnes du curseur grâce au ResultSetMetaData.
             */
            ResultSetMetaData lrsmd = lrs.getMetaData();
            // Nombre de colonnes du curseur
            int liColonnes = lrsmd.getColumnCount();
            // Noms des colonnes de la table
            tEntetes = new Object[liColonnes];
            for (int i = 0; i < liColonnes; i++) {
                tEntetes[i] = lrsmd.getColumnName(i + 1);
            }

            /* 
             * Pour l'insertion des données de la table dans la jTableArrondissement
             * Pour obtenir le nombre d'enregistrements et pouvoir dimensionner le tableau,
             * il faut se positionner sur le dernier enregistrement.
             */
            lrs.last();
            int liLignes = lrs.getRow();
            tDataTable = new Object[liLignes][liColonnes];

            lrs.beforeFirst();
            int i = 0;
            // Balayage des lignes
            while (lrs.next()) {
                // Balayage des colonnes pour construire une ligne
                tDataLigne = new Object[liColonnes];
                for (int j = 0; j < liColonnes; j++) {
                    if (lrs.getObject(j + 1) == null) {
                        tDataLigne[j] = "NUL";
                    } else {
                        tDataLigne[j] = lrs.getObject(j + 1).toString();
                    }
                }
                tDataTable[i] = tDataLigne;
                i++;
            }
            
            // --- Affectation des tableaux d'objets a la JTable
            idtm = new DefaultTableModel(tDataTable, tEntetes);
            jTable1.setModel(idtm);
            
            // Fermetures
            lrs.close();
            lpst.close();
            
            
            /*
             Dyn des JLabels et des JTextFields
             */
            int iiPosX = 0;
            int iiPosY = 0;
            tLabels = new JLabel[tEntetes.length];
            tJTexts = new JTextField[tEntetes.length];

            jPanel1.removeAll();
            
            for (i = 0; i < tLabels.length; i++) {
                tLabels[i] = new JLabel(tEntetes[i].toString());
                tJTexts[i] = new JTextField();

                jPanel1.add(tLabels[i]);

                tLabels[i].setSize(200, 30);
                tLabels[i].setLocation(iiPosX + 10, iiPosY);
                tLabels[i].setVisible(true);

                jPanel1.add(tJTexts[i]);
                tJTexts[i].setSize(150, 30);
                tJTexts[i].setLocation(iiPosX + 200, iiPosY);
                tJTexts[i].setVisible(true);

                iiPosY += 30;

            }
            jPanel1.setBounds(jPanel1.getX(), jPanel1.getY(), iiPosX, iiPosY);

            jPanel1.repaint();

        } catch (SQLException e) {
            jLabelMessage.setText(e.getMessage());
        }
    }//GEN-LAST:event_jComboBoxGenerateItemStateChanged

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        int liRow = jTable1.getSelectedRow();
        for (int i = 0; i < tJTexts.length; i++) {
            jTable1.setValueAt(tJTexts[i].getText().toString(), liRow, i);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        // 
        for (int i = 0; i < tJTexts.length; i++) {
            tJTexts[i].setText("");
        }
        tJTexts[0].requestFocus();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        // 
        int liRow = jTable1.getSelectedRow();
        for (int i = 0; i < jTable1.getColumnCount(); i++) {
            tJTexts[i].setText(jTable1.getValueAt(liRow, i).toString());
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        // 
        int liRow = jTable1.getSelectedRow();
        if (liRow >= 0) {
            idtm.removeRow(liRow);

        } else {
            jLabelMessage.setText("Abruti, sélectionne au moins une ligne !!!");
        }
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox jComboBoxGenerate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelMessage;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
